-- Baseline domain schema: customer -> account -> transaction (the ~5M-row table),
-- statement_run -> statement, and a standalone comm_template table.
--
-- Deliberately NO secondary indexes here — only primary keys and foreign key
-- constraints. Every index this schema gets later arrives in its own migration,
-- justified by a measured EXPLAIN plan (see docs/PLAN.md, Investigation 2).

CREATE TABLE customer (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL,
    segment    TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE account (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT NOT NULL REFERENCES customer (id),
    product_type TEXT NOT NULL,
    opened_at    DATE NOT NULL,
    status       TEXT NOT NULL
);

-- "transaction" is an unreserved keyword in PostgreSQL — legal unquoted as an
-- identifier (only reserved as a function/type name), so no quoting needed here
-- or in the entity's @Table.
CREATE TABLE transaction (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  BIGINT NOT NULL REFERENCES account (id),
    txn_date    DATE NOT NULL,
    amount      NUMERIC(12, 2) NOT NULL,
    description TEXT
);

CREATE TABLE statement_run (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_date DATE NOT NULL,
    channel  TEXT NOT NULL,
    status   TEXT NOT NULL,
    version  BIGINT NOT NULL DEFAULT 0
);

-- id stays IDENTITY on purpose: Investigation 4 (M7) migrates it to a pooled
-- SEQUENCE to demonstrate the IDENTITY-vs-SEQUENCE JDBC batching gotcha.
CREATE TABLE statement (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_run_id BIGINT NOT NULL REFERENCES statement_run (id),
    account_id       BIGINT NOT NULL REFERENCES account (id),
    period_start     DATE NOT NULL,
    period_end       DATE NOT NULL,
    total_debits     NUMERIC(14, 2) NOT NULL,
    total_credits    NUMERIC(14, 2) NOT NULL,
    closing_balance  NUMERIC(14, 2) NOT NULL,
    document_ref     TEXT NOT NULL
);

CREATE TABLE comm_template (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL,
    channel       TEXT NOT NULL,
    body_template TEXT NOT NULL,
    version       INT NOT NULL
);
